### ISSUE TITLE
`frontdoor` api.yaml fix

### ISSUE THREAD

**Issue by JunyiYi** [Azure/autorest.cli#14]
The issues below are block issues.

* Remove [`prefix`](https://github.com/Azure/magic-module-specs/blob/master/frontdoor/api.yaml#L3).
* Escape the single quote `'` in `description` [here](https://github.com/Azure/magic-module-specs/blob/master/frontdoor/api.yaml#L988), [here](https://github.com/Azure/magic-module-specs/blob/master/frontdoor/api.yaml#L1144), [here](https://github.com/Azure/magic-module-specs/blob/master/frontdoor/api.yaml#L1224) and [here](https://github.com/Azure/magic-module-specs/blob/master/frontdoor/api.yaml#L1282).
* Integer types in `properties` should be **`Api::Type::Integer`** instead of [`Api::Azure::Type::Integer`](https://github.com/Azure/magic-module-specs/blob/master/frontdoor/api.yaml#L1029).
* Nested Object should contain sub-properties. For example: [`routeConfiguration`](https://github.com/Azure/magic-module-specs/blob/master/frontdoor/api.yaml#L995-L999).
* Rename ['list'](https://github.com/Azure/magic-module-specs/blob/master/frontdoor/api.yaml#L902) to **`list_by_subscription`**.

Here are the issues not blocking us.

* Remove [`name`](https://github.com/Azure/magic-module-specs/blob/master/frontdoor/api.yaml#L1319-L1324) because it is duplicated with [`name`](https://github.com/Azure/magic-module-specs/blob/master/frontdoor/api.yaml#L926-L932).
* Remove ['input: true'](https://github.com/Azure/magic-module-specs/blob/master/frontdoor/api.yaml#L1316) from pure output attributes.

**Comment by chunyu3** [comment]
All the links are invalid, and so cannot figure the issue list above. But according to description most problems are fixed.
close this ticket.
