### ISSUE TITLE
`softwareupdateconfiguration` api.yaml fix

### ISSUE THREAD

**Issue by JunyiYi** [Azure/autorest.cli#15]
Here are the blocking issues:

* Escape single quote `'` [here](https://github.com/Azure/magic-module-specs/blob/master/softwareupdateconfiguration/api.yaml#L1039), [here](https://github.com/Azure/magic-module-specs/blob/master/softwareupdateconfiguration/api.yaml#L1054).
* ['Api::Azure::Type::Integer'](https://github.com/Azure/magic-module-specs/blob/master/softwareupdateconfiguration/api.yaml#L1037) should be **`Api::Type::Integer`**.
* Remove [`prefix`](https://github.com/Azure/magic-module-specs/blob/master/softwareupdateconfiguration/api.yaml#L3).
* Nested Object should contain sub-properties [here](https://github.com/Azure/magic-module-specs/blob/master/softwareupdateconfiguration/api.yaml#L995-L1000).
* `resource_type_name: 'Virtual Machine'` is required for [this `Api::Azure::Type::ResourceReference`](https://github.com/Azure/magic-module-specs/blob/master/softwareupdateconfiguration/api.yaml#L959-L964). And `resource_type_name: Subscription` is required for [this `ResourceReference`](https://github.com/Azure/magic-module-specs/blob/master/softwareupdateconfiguration/api.yaml#L983-L988).
* Rename [`list`](https://github.com/Azure/magic-module-specs/blob/master/softwareupdateconfiguration/api.yaml#L815) to **`list_by_parent`**.

Here are the non-blocking issues:

* Remove [`name`](https://github.com/Azure/magic-module-specs/blob/master/softwareupdateconfiguration/api.yaml#L1222-L1227) because it is duplicated with [`name`](https://github.com/Azure/magic-module-specs/blob/master/softwareupdateconfiguration/api.yaml#L852-L858).
* Please remove [`input: true`](https://github.com/Azure/magic-module-specs/blob/master/softwareupdateconfiguration/api.yaml#L1231) for pure output attributes.
* It seems that the type of ['nextRunOffsetMinutes'](https://github.com/Azure/magic-module-specs/blob/master/softwareupdateconfiguration/api.yaml#L221) should be `Api::Azure::SDKTypeDefinition::FloatObject` instead of `IntegerObject` from its [definition in Go SDK](https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/automation/mgmt/2018-06-30-preview/automation/models.go#L7797). Can you double-check about that?

**Comment by chunyu3** [comment]
Hi Junyi
All the links in above comment are not valid anymore. 
Would you please help to refine it so that I can clear understand the issues to fix?
Thanks,

**Comment by chunyu3** [comment]
close this issue since the links are invalid.
