### ISSUE TITLE
[MM] Autorest.cli fails to generate api.yaml for AppServiceCertificateOrders

### ISSUE THREAD

**Issue by hund030** [Azure/autorest.cli#18]
I'm using this[ json file](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.CertificateRegistration/stable/2018-02-01/AppServiceCertificateOrders.json) generating api.yaml but get below warning and nothing generated for magic-modules.

> WARNING: Cannot read property 'x-ms-examples' of undefined -- "TypeError: Cannot read property 'x-ms-examples' of undefined\n    at new ExampleProcessor (/autorest.cli/dist/ExampleProcessor.js:17:62)\n    at Object.<anonymous> (/autorest.cli/dist/index.js:77:36)\n    at Generator.next (<anonymous>)\n    at fulfilled (/autorest.cli/dist/index.js:4:58)"

Seems it's because the rest-api-specs missing some examples for cli but I expect autorest.cli can generate something for magic-modules even with an incomplete rest-api-specs.

**Comment by chunyu3** [comment]
The issue does not exist in latest autorest.cli.
close the issue.
