### ISSUE TITLE
[MM]Porperty Type Error in api.yaml

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.cli#26]
Property Name | Original Type | Should Be
-- | -- | --
'excludedKbNumbers' | !ruby/object:Api::Type::String | !ruby/object:Api::Type::Array   (item_type: Api::Type::String)
'includedKbNumbers' | !ruby/object:Api::Type::String | !ruby/object:Api::Type::Array   (item_type: Api::Type::String)
'excludedPackageNameMasks' | !ruby/object:Api::Type::String | !ruby/object:Api::Type::Array   (item_type: Api::Type::String)
'includedPackageNameMasks' | !ruby/object:Api::Type::String | !ruby/object:Api::Type::Array   (item_type: Api::Type::String)
'nonAzureComputerNames' | !ruby/object:Api::Type::String | !ruby/object:Api::Type::Array   (item_type: Api::Type::String)
'locations' | !ruby/object:Api::Type::String | !ruby/object:Api::Type::Array   (item_type: Api::Type::String)
'weekDays' | !ruby/object:Api::Type::String | !ruby/object:Api::Type::Array   (item_type: Api::Type::String)
  |   |  
'monthDays' | !ruby/object:Api::Type::String | !ruby/object:Api::Type::Array   (item_type: Api::Type::Integer)
  |   |  
'includedPackageNameMasks' | !ruby/object:Api::Azure::Type::ResourceReference | !ruby/object:Api::Type::Array   (item_type: Api::Azure::Type::ResourceReference)
'scope' | !ruby/object:Api::Azure::Type::ResourceReference | !ruby/object:Api::Type::Array   (item_type: Api::Azure::Type::ResourceReference)
  |   |  
'azureQueries' | !ruby/object:Api::Type::NestedObject | !ruby/object:Api::Type::Array   (item_type: !ruby/object:Api::Type::NestedObject)
'nonAzureQueries' | !ruby/object:Api::Type::NestedObject | !ruby/object:Api::Type::Array   (item_type: !ruby/object:Api::Type::NestedObject)
'advancedSchedule' | !ruby/object:Api::Type::NestedObject | !ruby/object:Api::Type::Array   (item_type: !ruby/object:Api::Type::NestedObject)
'monthlyOccurrences' | !ruby/object:Api::Type::NestedObject | !ruby/object:Api::Type::Array   (item_type: !ruby/object:Api::T

**Comment by chunyu3** [comment]
The 'SequeceType' is not correctly translated to Array type.

**Comment by zikalino** [comment]
what is the source swagger?
I will check it e2e and tell you how to solve it

**Comment by zikalino** [comment]
if option.IsList is true, you should do something like this:

item_type = data_type
data_type = !ruby/object:Api::Type::Array

**Comment by chunyu3** [comment]
'advancedSchedule' should be '!ruby/object:Api::Type::NestedObject'

and 'includedPackageNameMasks' and 'scope', the item_type shoud be Api::Type::String

**Comment by chunyu3** [comment]
PR: https://github.com/Azure/autorest.cli/pull/31
