### ISSUE TITLE
[MM]It doesn't generate the required properties for separated update function

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/autorest.cli#60]
It doesn't generate the required properties for separated update function in api.yml and threw below error message while running MM command. MM just generates partially properties like below snapshot. After investigated, MM failed in file resource.erb of MM since it is requesting a property "/" under update function but it doesn't exist in api.yml so that it failed. So the root cause is that autorest.cli doesn't generate the property "/" and other required properties in api.yml. So please have a look and fix it. Thanks.

Resource in azure rest api specs: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/hanaonazure/resource-manager/readme.md

It just generated porperties "resourceGroupName" and "sapMonitorName". It should also generate other properties like "/", "/location", "/properties", "/hanaSubnet" and so on.

File resource.erb of MM:
![image](https://user-images.githubusercontent.com/19754191/68838059-c8dffd00-06f8-11ea-98e5-1d5eed786905.png)

Error message:
![image](https://user-images.githubusercontent.com/19754191/68837979-ab129800-06f8-11ea-93a0-de41559e1174.png)

![image](https://user-images.githubusercontent.com/19754191/68837364-5e7a8d00-06f7-11ea-9501-591a3c4b58ed.png)
 
It should generate the properties like create function. Please see below snapshot.
![image](https://user-images.githubusercontent.com/19754191/68837444-8538c380-06f7-11ea-9886-9e7872d0b9d0.png)

**Comment by chunyu3** [comment]
In swagger json file, the update file has no properties parameter 'SapMonitorParameter' definition as create.
create:
"put": {
        "tags": [
          "HanaOnAzure"
        ],
        "operationId": "SapMonitors_Create",
        "x-ms-long-running-operation": true,
        "summary": "Creates a SAP monitor.",
        "description": "Creates a SAP monitor for the specified subscription, resource group, and resource name.",
        "x-ms-examples": {
          "Create a SAP Monitor": {
            "$ref": "./examples/SapMonitors_Create.json"
          }
        },
        "parameters": [
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
          {
            "$ref": "#/parameters/SubscriptionIdParameter"
          },
          {
            "$ref": "#/parameters/ResourceGroupNameParameter"
          },
          {
            "$ref": "#/parameters/SapMonitorNameParameter"
          },
          {
            "$ref": "#/parameters/SapMonitorParameter"
          }
        ],


update:
"patch": {
        "tags": [
          "HanaOnAzure"
        ],
        "operationId": "SapMonitors_Update",
        "summary": "Patches the Tags field of a SAP monitor.",
        "description": "Patches the Tags field of a SAP monitor for the specified subscription, resource group, and monitor name.",
        "x-ms-examples": {
          "Update Tags field of a SAP monitor": {
            "$ref": "./examples/SapMonitors_PatchTags.json"
          },
          "Delete Tags field of a SAP monitor": {
            "$ref": "./examples/SapMonitors_PatchTags_Delete.json"
          }
        },
        "parameters": [
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
          {
            "$ref": "#/parameters/SubscriptionIdParameter"
          },
          {
            "$ref": "#/parameters/ResourceGroupNameParameter"
          },
          {
            "$ref": "#/parameters/SapMonitorNameParameter"
          },
          {
            "$ref": "#/parameters/TagsParameter"
          }
        ],

That's why there is no properties in update function as in create function.

**Comment by chunyu3** [comment]
Need to confirm with swagger spec team about it

**Comment by neil-yechenwei** [comment]
Thanks for your comment. I've filed an issue on swagger repo. This is the issue link https://github.com/Azure/azure-rest-api-specs/issues/7789.
