### ISSUE TITLE
[MM]The api.yml shouldn't be generated to package folder for SAP Monitor

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/autorest.cli#61]
The api.yml shouldn't be generated to package folder like "package-2017-11" for SAP Monitor. It should be generated to resource folder like "hanaonazuresapmonitor".
![image](https://user-images.githubusercontent.com/19754191/68841966-7f93ab80-0700-11ea-9bd0-69d0bee7bf6d.png)

Command: 
C:\terraform\projects\autorest.cli>autorest --cli --use=C:/terraform/projects/autorest.cli --mm --output-folder=C:/terraform/generated/abc C:\terraform\projects\azure-rest-api-specs\specification\hanaonazure\resource-manager\readme.md

Added below command to readme.md for hanaibazure:
![image](https://user-images.githubusercontent.com/19754191/68842469-64756b80-0701-11ea-9c58-40051b2dfad5.png)

**Comment by chunyu3** [comment]
We add package into the magic-modules-input-files folder path since we will support different tags of a resource.

**Comment by neil-yechenwei** [comment]
Got it. Thanks.
