### ISSUE TITLE
Properties missing in several resources

### ISSUE THREAD

**Issue by JunyiYi** [Azure/autorest.cli#7]
From the documentation, there are a lot of properties (request body) in API Management Diagnostic: https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-01-01/diagnostic/createorupdate#request-body.

But the generated file only contains very few: https://github.com/Azure/magic-module-specs/blob/master/products/azure_rm_apimanagementdiagnostic/api.yaml#L50.

Maybe I am looking at the wrong file?

**Comment by zikalino** [comment]
I have updated input file version to the latest.
I was using one year old version as there was some problem loading newest input files which is now solved.
