### ISSUE TITLE
Several issues in softwareupdateconfiguration

### ISSUE THREAD

**Issue by JunyiYi** [Azure/autorest.cli#8]
1. [x] `read` is missing. Here is the API definition: https://docs.microsoft.com/en-us/rest/api/automation/softwareupdateconfigurations/getbyname.
2. [x] Type of duration is missing: https://github.com/Azure/magic-module-specs/blob/master/softwareupdateconfiguration/api.yaml#L91, https://github.com/Azure/magic-module-specs/blob/master/softwareupdateconfiguration/api.yaml#L166. I would say to use `!ruby/object:Api::Azure::SDKTypeDefinition::ISO8601DurationObject`.
3. [x] If the type is float: https://github.com/Azure/magic-module-specs/blob/master/softwareupdateconfiguration/api.yaml#L212, just using `!ruby/object:Api::Azure::SDKTypeDefinition::FloatObject`. If it is interger, then using one of the integer types specified here: https://github.com/Azure/magic-module-specs/blob/master/RESOURCE_SPEC.md#sdk-operation-request.
4. [x] Use `!ruby/object:Api::Azure::SDKTypeDefinition::ISO8601DateTimeObject` for date time: https://github.com/Azure/magic-module-specs/blob/master/softwareupdateconfiguration/api.yaml#L209.

For the corresponding types defined in `properties`, please use `!ruby/object:Api::Azure::Type::ISO8601Duration`, `!ruby/object:Api::Azure::Type::ISO8601DateTime` and the number types specified here: https://github.com/Azure/magic-module-specs/blob/master/RESOURCE_SPEC.md#devops-user-interface-definition.

**Comment by zikalino** [comment]
(1), (2), (3) and (4) are fixed in the new cumulative pr:

https://github.com/Azure/magic-module-specs/pull/24

Please verify and close this issue.

**Comment by zikalino** [comment]
Sorry, made mistake, (1) still needs fixing

**Comment by zikalino** [comment]
(1) is now fixed as well and included in the pr

**Comment by JunyiYi** [comment]
Verified.
