### ISSUE TITLE
Several issues in batchapplication

### ISSUE THREAD

**Issue by JunyiYi** [Azure/autorest.cli#9]
Here is the current api.yaml: https://github.com/Azure/magic-module-specs/blob/master/batchapplication/api.yaml.

I found several issues:

* [x] The ID (output property) is missing in properties
* [x] Go variable name should use `camelCase` instead of `PascalCase` (it is different from go_field_name and go_type_name, they should use `PascalCase`): https://github.com/Azure/magic-module-specs/blob/master/batchapplication/api.yaml#L33

**Comment by zikalino** [comment]
Including id in properties is now fixed.
Variable names are camelCase.

Creating cumulative PR with these fixes

**Comment by zikalino** [comment]
https://github.com/Azure/magic-module-specs/pull/24

Please verify & close the issue.

**Comment by JunyiYi** [comment]
Verified.-
